routes:

collections:
  /salmo-119/:
    permalink: /salmo-119/{slug}/
    filter: primary_tag:salmo119

  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /{slug}/
  author: /autor/{slug}/
